name: pedrolino
version: 0.0.1
base: core18
summary: Bug reproducer
description: |
  Minimal reproducer of bug encountered while working on the
  MicroStack snap.
grade: stable
confinement: classic  # This mirrors MicroStack, which must be classicly confined for now.
environment:
  PATH: $SNAP/usr/sbin:$SNAP/usr/bin:$SNAP/sbin:$SNAP/bin:$PATH

apps:
  test:
    command: bin/pedrolino

  python:
    command: usr/bin/python3

parts:
  pedrolino:
    plugin: python
    python-version: python3
    source: src/
